CONFIG_FILE="${1:-./BRIEF_config.sh}"
source "$CONFIG_FILE"
export CUDA_VISIBLE_DEVICES=0 
GRAD_JOB_NAME="$JOB_NAME_WARM-gradient"

LOG_FILE=$(log_file "$GRAD_JOB_NAME")
bash "$GRAD_SCRIPT_PATH" "$DATA_FILE" "$MODEL_PATH_GRAD" "$OUTPUT_PATH_GRAD" "$DIM" "$GRADIENT_TYPE" "$INFO_TYPE" "$MAX_LENGTH" > "$LOG_FILE" 2>&1